feat: make the install of rack instrumentation by grape instrumentation optional
open-telemetry/opentelemetry-ruby-contrib pull request #1043
Opened 2024-06-27 13:06 UTC by chrisholmes

In some circumstances we may want to defer the installation of the rack instrumentation that is orchestrated during the grape instrumentation installation. For example, we may want to customise the installation of the rack instrumentation or we can rely on the installation being orchestrated by another framework's instrumentation (such as when Grape is mounted with Rails).

This change allows for Grape to skip the installation of the Rack instrumentation so that it can manually installed at a later time.

2024-06-27 21:05 UTC, kaylareopelle requested changes

2024-07-01 14:20 UTC, chrisholmes commented on instrumentation/grape/lib/opentelemetry/instrumentation/grape/instrumentation.rb
> +        option :install_rack, default: true, validate: :boolean
does the new change work?

2024-07-01 16:55 UTC, simi approved these changes

2024-07-01 22:10 UTC, kaylareopelle commented on instrumentation/grape/lib/opentelemetry/instrumentation/grape/instrumentation.rb
> +        option :install_rack, default: true, validate: :boolean
It looks great! Thank you!

<img width="1767" alt="Screenshot 2024-07-01 at 3 09 49 PM" src="https://github.com/open-telemetry/opentelemetry-ruby-contrib/assets/87386821/18924258-05a7-4835-9896-f1aa722a8be6">

2024-07-01 22:10 UTC, kaylareopelle approved these changes

2024-07-02 17:24 UTC, merged