fix: Format gat commands
open-telemetry/opentelemetry-ruby-contrib pull request #1312
Opened 2024-12-19 19:40 UTC by robertlaurin

2024-12-19 20:04 UTC, plantfansam approved these changes

2024-12-19 20:12 UTC, ericmustin approved these changes

2024-12-20 04:26 UTC, fbogsany approved these changes
Looks gat to me!

2024-12-20 04:29 UTC, fbogsany requested changes
Looks like `gat` isn't supported in (one of?) the `dalli` version we test against. We should consider whether to bump the minimum version we support.

2024-12-20 04:31 UTC, fbogsany commented on instrumentation/dalli/test/opentelemetry/instrumentation/dalli/instrumentation_test.rb
> +      dalli.gat('foo')
`gat` was [added to `dalli` in 3.0.0](https://github.com/petergoldstein/dalli/blob/f72450aeb23a1a553299157f2a070eb421994b2c/CHANGELOG.md?plain=1#L178). We could `skip` if the dalli version is < 3.0.0 or set 3.0.0 as the min supported version.

2024-12-20 04:32 UTC, fbogsany commented on instrumentation/dalli/test/opentelemetry/instrumentation/dalli/instrumentation_test.rb
> +      dalli.gat('foo')
My preference is to `skip`, since we only need it in this test, and the test matrix _should_ cover 3.0.0.

2025-01-11 00:30 UTC, kaylareopelle approved these changes

2025-01-14 20:19 UTC, fbogsany approved these changes

2025-01-14 20:24 UTC, merged