[WIP] feat: Add ActiveStorage instrumentation
open-telemetry/opentelemetry-ruby-contrib pull request #1313
Opened 2024-12-20 07:30 UTC by ymtdzzz

## Description
Adding support for instrumenting ActiveStorage using ActiveSupport::Notification.

related: #1307 

## Test
TBU

2025-01-16 16:34 UTC, xuan-cao-swi commented on instrumentation/all/opentelemetry-instrumentation-all.gemspec
> +  spec.add_dependency 'opentelemetry-instrumentation-active_storage', '~> 0.0.0'
I think it's best to include this instrumentation to -all and -rails once this pr gets merged and released

2025-01-16 16:36 UTC, xuan-cao-swi commented on instrumentation/active_storage/test/test_helpers/app_config.rb
> +      ActiveStorage::Current.url_options = { host: 'http://example.com' }
nit: why they need to be separate line?

2025-01-16 16:38 UTC, xuan-cao-swi commented on instrumentation/active_storage/lib/opentelemetry/instrumentation/active_storage/version.rb
> +      VERSION = '0.0.0'
let's make it '0.1.0' as initial release version.

2025-01-18 01:41 UTC, kaylareopelle requested changes
Thank you, @ymtdzzz! I'm looking forward to OTel to offering ActiveStorage support.

2025-01-18 01:41 UTC, kaylareopelle commented on instrumentation/active_storage/lib/opentelemetry/instrumentation/active_storage/instrumentation.rb
> +      #
It looks like the default is missing on just this config:
```suggestion
      #
      # - `array` **default** `[]`
      #
```

2025-01-18 01:41 UTC, kaylareopelle commented on instrumentation/active_storage/opentelemetry-instrumentation-active_storage.gemspec
> +  spec.add_development_dependency 'rubocop', '~> 1.69.1'
We're about to merge a PR that'll bump Rubocop to 1.70.0:
```suggestion
  spec.add_development_dependency 'rubocop', '~> 1.70.0'
```

2025-01-18 01:41 UTC, kaylareopelle commented on instrumentation/active_storage/test/test_helper.rb
> +
We recently had to add explicit requires to `'logger'` in the test helpers for some Rails-related libraries to avoid uninitialized constant errors: #1345 

Rails added `logger` as a dependency in Rails 7.1 and above, but since we still support 7.0, we need to require it here.
```suggestion

require 'logger'
```

2025-01-18 01:41 UTC, kaylareopelle commented on instrumentation/active_storage/test/test_helpers/app_config.rb
> +      ActiveStorage::Current.host = 'http://example.com'
Cleanup related to dropping 6.1 support:
```suggestion
```

2025-01-18 01:41 UTC, kaylareopelle commented on instrumentation/all/opentelemetry-instrumentation-all.gemspec
> +  spec.add_dependency 'opentelemetry-instrumentation-active_storage', '~> 0.0.0'
I think that's a good call. However, if this is added to -rails, I don't think it also has to be added to -all, because -all requires -rails.

2025-01-18 01:41 UTC, kaylareopelle commented on .github/actions/test_gem/action.yml
> +      run: sudo apt update && sudo apt install -y imagemagick
Thanks for adding this service here! We also have a `docker-compose.yml` to allow developers to run services locally. Would you mind adding ImageMagick to that file too?

2025-01-18 06:31 UTC, ymtdzzz commented on instrumentation/active_storage/Appraisals
> +%w[6.1.0 7.0.0 7.1.0].each do |version|
Thank you for pointing that out! I fixed in https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1313/commits/c6ea05f3251f20ac2b4c858823e55b101ffebd80

2025-01-18 06:32 UTC, ymtdzzz commented on instrumentation/active_storage/lib/opentelemetry/instrumentation/active_storage/instrumentation.rb
> +        MINIMUM_VERSION = Gem::Version.new('6.1.0')
This is also fixed in https://github.com/open-telemetry/opentelemetry-ruby-contrib/commit/c6ea05f3251f20ac2b4c858823e55b101ffebd80

2025-01-18 06:33 UTC, ymtdzzz commented on instrumentation/active_storage/test/test_helpers/app_config.rb
> +      ActiveStorage::Current.host = 'http://example.com'
thanks, this is also fixed in https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1313/commits/c6ea05f3251f20ac2b4c858823e55b101ffebd80 !

2025-01-18 06:35 UTC, ymtdzzz commented on instrumentation/active_storage/lib/opentelemetry/instrumentation/active_storage/instrumentation.rb
> +      #
I agree, fixed in https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1313/commits/613e1b6f528f6ea077e1d64f1013d04a6ebb1e8a

2025-01-18 06:38 UTC, ymtdzzz commented on instrumentation/active_storage/opentelemetry-instrumentation-active_storage.gemspec
> +  spec.add_development_dependency 'rubocop', '~> 1.69.1'
Thank you for letting me know, I've matched the version with other packages!
https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1313/commits/b98fadfd952dcaa834725cd16dd2daf0f332eca1

2025-01-18 06:40 UTC, ymtdzzz commented on instrumentation/active_storage/test/test_helper.rb
> +
That makes sense, I added explicit `logger` require. https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1313/commits/da97949a3c453e649105433c331b53e9c923c96c

2025-01-18 06:48 UTC, ymtdzzz commented on .github/actions/test_gem/action.yml
> +      run: sudo apt update && sudo apt install -y imagemagick
As you said, the test for ActiveStorage instrumentation did not pass due to the lack of ImageMagick inside the container. So I added it to the `Dockerfile` and confirmed that the test passed. https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1313/commits/ed63c881511ca6390f8db7e1ee827fdaa195c820

```
❯ docker compose run app /bin/ash
/app $ cd instrumentation/active_storage/
/app/instrumentation/active_storage $ bundle install
/app/instrumentation/active_storage $ bundle exec appraisal install
/app/instrumentation/active_storage $ bundle exec appraisal rake test
...

# Running:
                                                                                                                                                                                                                                                                                                                     
..........................
                                                                                                                                                                                                                                                                                                                     
Finished in 0.976136s, 26.6356 runs/s, 101.4203 assertions/s.
26 runs, 99 assertions, 0 failures, 0 errors, 0 skips
```

2025-01-18 06:50 UTC, ymtdzzz commented on instrumentation/active_storage/test/test_helpers/app_config.rb
> +      ActiveStorage::Current.url_options = { host: 'http://example.com' }
Thanks, I fixed unnecessary conditions in https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1313/commits/bfae8c715ee3f830658cae4748a0114375e5adcd !

2025-01-18 06:56 UTC, ymtdzzz commented on instrumentation/all/opentelemetry-instrumentation-all.gemspec
> +  spec.add_dependency 'opentelemetry-instrumentation-active_storage', '~> 0.0.0'
Make sense. In https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1313/commits/d6979a7eff054d8e7f2c67dd62e0929eff4b3554 , I removed -active_storage from -all .
I'll create another PR to -active_storage this to -rails after this PR is relesed.

2025-01-18 06:57 UTC, ymtdzzz commented on instrumentation/active_storage/lib/opentelemetry/instrumentation/active_storage/version.rb
> +      VERSION = '0.0.0'
changed the version in https://github.com/open-telemetry/opentelemetry-ruby-contrib/commit/d6979a7eff054d8e7f2c67dd62e0929eff4b3554

2025-01-21 22:04 UTC, kaylareopelle reviewed
Thanks for all the updates! 😄 

The last thing I can think of would be to update the CODEOWNERS file to add your name to the list of reviewers. The OpenTelemetry Ruby team needs help from end users and other experts in the community to maintain our instrumentation. Since you built this Active Storage instrumentation, we'd love for you to help us maintain the library going forward. By becoming a CODEOWNER, you would be added as a reviewer to any PR opened to update the `instrumentaiton/active_storage` code. We may also tag you directly in issues raised regarding the Active Storage instrumentation. 

Would you be comfortable with this? 

I'd also like @xuan-cao-swi to take another look when he has a chance.

2025-01-22 04:44 UTC, ymtdzzz commented
@kaylareopelle 

Thank you for the suggestion! 

Of course I'm happy to help with reviews and issues regarding the instrumentation!
I've added my name to the `CODEOWNERS` in https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1313/commits/9221f0dec29b001462b890edcbd8ef71b9e98e77 .

I'm looking forward to collaborating with the team!

2025-01-22 22:23 UTC, xuan-cao-swi approved these changes

2025-01-27 21:05 UTC, kaylareopelle approved these changes
Thank you! 🚀

2025-01-28 21:10 UTC, merged

2025-01-29 14:32 UTC, arielvalentin commented on instrumentation/active_storage/lib/opentelemetry/instrumentation/active_storage/version.rb
> +      VERSION = '0.1.0'
@open-telemetry/ruby-contrib-approvers Our automated release tooling handles versioning. For initial releases this should have been set to `0.0.0`

The instrumentation generator seeds the version here:

https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/.instrumentation_generator/templates/lib/instrumentation/instrumentation_name/version.rb.tt#L10 

That along with the empty CHANGELOG signals to the release tooling that this specific version will need to be an "initial release" of the gem https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/.instrumentation_generator/templates/CHANGELOG.md.tt

2025-01-29 22:24 UTC, kaylareopelle commented on instrumentation/active_storage/lib/opentelemetry/instrumentation/active_storage/version.rb
> +      VERSION = '0.1.0'
Thanks for pointing this out, Ariel. I'm sorry about missing it before the merge.