Removed appraise for 1.x
open-telemetry/opentelemetry-ruby-contrib pull request #554
Opened 2023-07-11 10:57 UTC by Anu-MT

This PR is for:
Upgrade minimal gemspec dependencies to Sinatra > 2
Issue:  https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/364

2023-07-12 20:13 UTC, ericmustin requested changes

2023-07-12 20:13 UTC, ericmustin commented on instrumentation/sinatra/Appraisals
> +
```suggestion
```

2023-07-13 16:53 UTC, ericmustin commented
@Anu-MT looks like just a quick rubocop error then shud be good to merge, ty for the contribution

2023-07-13 17:18 UTC, arielvalentin commented
@Anu-MT will you also be flowing up to update the minimum version requirements for the instrumentation itself?

2023-07-18 11:19 UTC, Anu-MT commented
Hi,

Yes, I would like to work on that as well. Will do it within this week.

Thanks,
Anu



On Thu, 13 Jul 2023, 6:18 pm Ariel Valentin, ***@***.***>
wrote:

> @Anu-MT <https://github.com/Anu-MT> will you also be flowing up to update
> the minimum version requirements for the instrumentation itself?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/554#issuecomment-1634618777>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AC424Z5AQL5NZNZE3AWOLPLXQAUWFANCNFSM6AAAAAA2F2LKIE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2023-08-15 16:26 UTC, closed without merging